"""Comments

Revision ID: 602f89744d69
Revises: f704ee49b433
Create Date: 2024-07-15 16:05:10.729020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602f89744d69'
down_revision: Union[str, None] = 'f704ee49b433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('post', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_path', sa.VARCHAR(), nullable=True))
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
